Wildcard Writing
ensdomains/ensips pull request #10
Opened 2024-10-10 20:17 UTC by pikonha

# ENSIP: Standardized Offchain Resolver for ENS

## Summary

This ENSIP proposes a standardized Offchain Resolver interface for managing ENS domains stored off the Ethereum mainnet.

## Key Points

* Standardizes methods for offchain domain registration, transfer, and record management
* Supports both database and Layer 2 implementations
* Integrates with EIP-5559 for offchain writing
* Introduces registerParams, register, transfer, and multicall functions
* Provides reference implementations for L1 and L2 resolvers

2024-10-21 10:38 UTC, dmrazzy reviewed
Wrap

2024-10-24 14:47 UTC, lucemans requested changes

2024-10-24 14:47 UTC, lucemans commented on ensips/TBD.md
> +# Wildcard Writing
```suggestion
# ENSIP-X: Wildcard Writing
```

2025-03-06 07:58 UTC, Arachnid approved these changes

2025-03-06 21:09 UTC, gskril commented
hey @pikonha can you please update the frontmatter to match the format in [template.md](https://github.com/ensdomains/ensips/blob/master/template.md?plain=1)? that's why the build is failing

2025-03-10 13:34 UTC, pikonha commented
done @gskril

2025-03-10 18:32 UTC, merged