Universal Resolution
ensdomains/ensips pull request #11
Opened 2024-10-14 21:20 UTC by TateB

2024-10-16 12:59 UTC, Arachnid requested changes
This needs to explicitly state that callers must handle CCIP-Read reverts.

2024-10-16 12:59 UTC, Arachnid commented on ensips/x.md
> +This is becoming more prevalent over time, especially with the introduction of wildcard resolution (ENSIP-10), and more recently cross-chain reverse resolution (ENSIP-19).
```suggestion
Resolution is becoming more involved over time, especially with the introduction of wildcard resolution (ENSIP-10), and more recently cross-chain reverse resolution (ENSIP-19).
```

2024-10-16 12:59 UTC, Arachnid commented on ensips/x.md
> +- `lookupAddress`: The address to resolve the name for, in **encoded** form.
This should clarify what encoding - text? Binary? Examples for, eg, Ethereum and Bitcoin would be valuable.

2025-01-16 19:25 UTC, makoto commented
Should the ENSIP mention upgrade paths or are they more of the implementation detail? I personally thinks it should be mentioned as A: if it's user initiated upgrade, there must be a public API that initiates the upgrade, B: If it's DAO initiated upgrade, there still needs a API DAO has to call and also the user should aware that the resolution logic is not immutable

2025-01-16 19:51 UTC, makoto commented on ensips/x.md
> +### reverse
Can `reverse` also handle multicall so that user can pass multiple cointypes?

2025-03-19 16:09 UTC, TateB commented
@Arachnid by "callers", do you mean clients? or UniversalResolver implementations?

2025-03-19 16:21 UTC, TateB commented on ensips/x.md
> +### reverse
i don't really see a use-case

2025-03-19 16:24 UTC, TateB commented
@makoto i don't think adding implementation detail on upgrade paths is worth it, upgradability is down to each individual implementation and it isn't particularly relevant to universal resolution itself imo

2025-03-19 16:26 UTC, TateB commented on ensips/x.md
> +### reverse
the implementation for `resolve` is graceful in preserving a single-call happy path, whereas you can't really preserve that for `reverse`.

2025-03-20 11:39 UTC, Arachnid reviewed
Can you add documentation for the errors defined in https://github.com/ensdomains/ens-contracts/pull/421/files#diff-895978e0de194cab98cef8af1c7de86d9a16ac5c37a1b33a5a28faf671f3bf14 too?

2025-03-27 17:07 UTC, Arachnid requested changes

2025-03-27 17:07 UTC, Arachnid commented on ensips/x.md
> +### reverse
What about batch reverse resolution - eg, for things like leaderboards?

2025-03-27 18:46 UTC, TateB commented on ensips/x.md
> +### reverse
there's not much of a difference between something like viem's native batching (via multicall), and what a batch for many names in reverse resolution would do. if there are specific patterns for ccip-read that wouldn't use a batch gateway but instead would go straight to the source gateway, there's always the option of creating a ccip-read friendly multicall contract that assumes that scenario is true.

2025-03-27 20:31 UTC, Arachnid commented on ensips/x.md
> +### reverse
Can't you make the same argument about forward resolution?

2025-03-27 20:38 UTC, TateB commented on ensips/x.md
> +### reverse
batching for many different names means finding many different resolvers, whereas batching many records for one name (forward) is only 1 resolution lookup when using a multicall array.
for forward lookups, it also allows the potential removal of reliance on the batch gateway for some calls.

2025-05-23 06:52 UTC, makoto commented on ensips/x.md
> +    name: "multicall",
Should this be the variable `name` indicating that it's same as other name variables specified at line 95 and 99?

2025-05-23 06:53 UTC, makoto commented on ensips/x.md
> +    name: "multicall",
same here

2025-05-24 03:10 UTC, adraffy commented
I think we should include [findResolver()](https://github.com/ensdomains/ens-contracts/blob/feature/default-reverse-resolver/contracts/universalResolver/IUniversalResolver.sol#L31-L39) in the interface too.

2025-05-26 04:07 UTC, adraffy commented on ensips/x.md
> +### reverse
This [PR](https://github.com/ensdomains/ens-contracts/pull/432) adds efficient batch reverse resolution for multiple addresses on a single reverse resolver (of a single coin type).  It does not do the forward check (as that would require calls to many resolvers, like Tate mentions) but this could be used as a building block for that functionality.

2025-05-28 04:03 UTC, TateB commented on ensips/x.md
> +### reverse
could be part of a future spec?

2025-05-28 04:04 UTC, TateB commented on ensips/x.md
> +    name: "multicall",
?

2025-05-28 04:07 UTC, TateB commented on ensips/x.md
> +    name: "multicall",
changed `name` to `functionName` in case that's what you were meaning

2025-07-28 22:30 UTC, adraffy commented
I moved a bunch of stuff around and tried to simplify it.

I wanted a pseudocode example for forward resolution, but couldn't come up with anything simple w/o including too many cases, so I just left the Solidity and TypeScript usage examples.

A lot of specific details are covered in other ENSIPs so instead of repeating myself, I link out as much as possible, and focus on the mechanics.

Under "Smart Execution", I mention ENSIP-X as a placeholder for "ENSIP: Resolver Features", which I'm working on right now.  Possibly, this explanation could be moved to that ENSIP, as this is (my take on) the best protocol for efficiently calling a resolver.

2025-08-06 03:55 UTC, TateB commented on ensips/x.md
> +UR has the following Solidity [interface](https://github.com/ensdomains/ens-contracts/blob/staging/contracts/universalResolver/IUniversalResolver.sol):
worth making this a permalink

2025-08-06 03:59 UTC, adraffy commented on ensips/x.md
> +UR has the following Solidity [interface](https://github.com/ensdomains/ens-contracts/blob/staging/contracts/universalResolver/IUniversalResolver.sol):
Changed

2025-08-06 04:02 UTC, TateB commented on ensips/x.md
> +This function performs ENS primary name resolution according to [ENSIP-19](./19.md).  Provided a [byte-encoded](./9) `lookupAddress` and desired `coinType`, it returns the verified primary `name` and
maybe add a note that specifies the primary name is verified but in unnormalised form, and that needs to be done separately

2025-08-06 04:40 UTC, adraffy commented on ensips/x.md
> +This function performs ENS primary name resolution according to [ENSIP-19](./19.md).  Provided a [byte-encoded](./9) `lookupAddress` and desired `coinType`, it returns the verified primary `name` and
ya, agreed. 

> If the primary `name` is [unnormalized](./15), eg. `normalize("Nick.eth") != "nick.eth"`, then `name` and `resolver` are invalid.

2025-08-06 05:07 UTC, merged

2025-08-06 05:13 UTC, makoto commented on ensips/x.md
> +
It took a while to figure out what this Pseudocode Example does. Can you add a sentense like below explaining what the example does?

`
findResolver() walks up the domain hierarchy from "sub.nick.eth" to find the first parent domain with a resolver set (finds one at "nick.eth"), returning that resolver's address, the namehash of the original full name "sub.nick.eth", and the byte offset (4) indicating where in the DNS-encoded name the resolver was found.
`

2025-08-06 05:13 UTC, makoto commented on ensips/x.md
> +This function performs ENS forward resolution using the `resolver` found by [`findResolver()`](#findresolver).  It provides a standard interface for interacting [ENSIP-1](./1) and [ENSIP-10](./10) re
Like you did at EIP3668(CCIP-Read), worth adding ENSIP-1(ENS Protocol) and ENSIP-10(Wildcard) so that people don't have to click ENSIP to figure out what they actually are

2025-08-06 05:13 UTC, makoto commented on ensips/x.md
> +UR automatically handles wrapping calldata and unwrapping responses when interacting with an [`IExtendedResolver`](./10#pseudocode) and safely interacts with contracts deployed before [EIP-140](https
EIP-140(REVERT instruction)

2025-08-06 05:13 UTC, makoto commented on ensips/x.md
> +This ENSIP standardizes [IUniversalResolver](#specification) (UR), an universal entrypoint for resolving ENS names.  UR incorporates onchain algorithms for [ENSIP-10](./10#pseudocode), [ENSIP-19](./1
Please put the title of each ENSIP (eg: ENSIP-10(Wildcard Resolution))

2025-08-06 05:13 UTC, makoto commented on ensips/23.md
> +
Is it worth noting that Smart Multicall allow you to combine multiple calls of one node, not being able to combine calls of multiple nodes? For example you can call addr and text of `vitalik.eth` in one call, but not combining `addr` of `vitalik.eth` and `nick.eth` even though you have to encode node in each call (for the backward compatibility purpose)

2025-08-06 06:28 UTC, adraffy commented on ensips/x.md
> +
It's defined in ENSIP-1.  Additionally, this section will need revisited with ENSv2 as the traversal method changes.

2025-08-06 06:30 UTC, adraffy commented on ensips/x.md
> +This function performs ENS forward resolution using the `resolver` found by [`findResolver()`](#findresolver).  It provides a standard interface for interacting [ENSIP-1](./1) and [ENSIP-10](./10) re
I've been using the policy where I hyperlink the first time I mention something, and then rarely again unless its far away or I link to a specific anchor.

We could change the policy to all ENSIP references are linked, as that's an easy ENSIP-repo wide change, but might be noisy.

2025-08-06 06:34 UTC, adraffy commented on ensips/23.md
> +
Yeah, agreed.  I was relying on the existing `resolve()` interpretation but that should probably be explicitly stated so it's clear.

Also, somewhere, we could document the multicall-like reverse primary name lookup that each `ChainReverseResolver` supports.  That could be an appendix of ENSIP-19 or a separate ENSIP.  It was mentioned in the comments of this ENSIP above.

2025-08-07 06:41 UTC, adraffy commented on ensips/x.md
> +UR automatically handles wrapping calldata and unwrapping responses when interacting with an [`IExtendedResolver`](./10#pseudocode) and safely interacts with contracts deployed before [EIP-140](https
Changed in new PR.

2025-08-07 06:59 UTC, adraffy commented on ensips/x.md
> +This function performs ENS forward resolution using the `resolver` found by [`findResolver()`](#findresolver).  It provides a standard interface for interacting [ENSIP-1](./1) and [ENSIP-10](./10) re
Changed in new PR, but only mentioned once.

https://github.com/ensdomains/ensips/pull/46

2025-08-07 07:00 UTC, adraffy commented on ensips/x.md
> +This ENSIP standardizes [IUniversalResolver](#specification) (UR), an universal entrypoint for resolving ENS names.  UR incorporates onchain algorithms for [ENSIP-10](./10#pseudocode), [ENSIP-19](./1
Changed in new PR.